name: Push Code to Backend Branch
on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master
    
    - name: Deploy backend
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: backend
        FOLDER: backend
        GITHUB_TOKEN: ${{ secrets.TOKEN }}