name: Deploy to GitHub Pages
on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Deploy frontend
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: frontend
        FOLDER: frontend
        GITHUB_TOKEN: ${{ secrets.TOKEN }}